/*
===============================================================================
Magnitude Analysis
===============================================================================
KPI:
    To measure data and aggregate results by specific dimensions
	in order to understand data distribution
	across different categories.
===============================================================================
*/

-- Find total customers by state 
SELECT 
customer_state,
COUNT (customer_key)  as Total_customers
FROM analytics.Customers
GROUP BY customer_state
ORDER BY Total_customers DESC
--===============================================
--find total products by category 
SELECT 
product_category_name,
COUNT(product_key) as Total_products
FROM analytics.Products
GROUP BY product_category_name
ORDER BY Total_products DESC
--===================================================
--ADD VOLUME COLUMN TO PRODUCTS TABLE
ALTER TABLE analytics.Products
 ADD  product_volume int 
 UPDATE analytics.Products
 SET product_volume = product_length_cm * product_width_cm * product_height_cm;
 --================================================================================
--What is the avg volumn in each category 
SELECT 
product_category_name,
Avg(product_volume )AS AVG_volumn
FROM analytics.Products
GROUP BY product_category_name 
ORDER BY AVG_volumn DESC
--========================================================================

--What is the total revenue generated for each category?
SELECT 
p.product_category_name,
SUM(o.price) AS Total_revenue
FROM analytics.Products p
LEFT JOIN analytics.Orders o
ON p.product_id=o.product_id
GROUP BY product_category_name 
ORDER BY Total_revenue DESC
--=========================================================
-- What is the total revenue generated by each customer?
SELECT 
       customer_key,
       SUM(payment_value) AS Total_revenue
FROM analytics.Orders
GROUP BY customer_key
ORDER BY Total_revenue DESC
--=================================
--- What is the distribution of revenues across state?
SELECT
   
    c.customer_state,
    SUM(o.payment_value) AS total_revenue
FROM analytics.Orders o
LEFT JOIN analytics.Customers c
    ON c.customer_key = o.customer_key
GROUP BY c.customer_state
ORDER BY total_revenue DESC;

--=======================================================
